name: Build

on:
  push:
    branches:
      - main

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20.19.4
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.4'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Setup Java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate Keystore Configuration
        shell: bash
        run: |
          echo "🔐 验证密钥库配置..."
          cd android
          
          # 解码密钥库文件
          echo ${{ secrets.KEYSTORE_STORE_FILE_BASE64 }} | base64 --decode > app/temp_validate.keystore
          
          # 验证密钥库文件是否存在
          if [ ! -f "app/temp_validate.keystore" ]; then
            echo "❌ 错误：密钥库文件解码失败"
            exit 1
          fi
          
          echo "✅ 密钥库文件解码成功"
          
          # 验证密钥库密码和别名
          echo "验证密钥库密码和别名..."
          keytool -list \
            -keystore app/temp_validate.keystore \
            -storepass '${{ secrets.KEYSTORE_PASSWORD }}' \
            -alias '${{ secrets.KEYSTORE_KEY_ALIAS }}' > /dev/null 2>&1
          
          if [ $? -eq 0 ]; then
            echo "✅ 密钥库密码和别名验证成功"
          else
            echo "❌ 错误：密钥库密码或别名不正确"
            rm -f app/temp_validate.keystore
            exit 1
          fi
          
          # 清理临时文件
          rm -f app/temp_validate.keystore
          echo "✅ 所有密钥验证通过"

      - name: Build Android Release
        shell: bash
        run: |
          cd android
          echo "🏗️ 开始构建发布版本..."
          echo ${{ secrets.KEYSTORE_STORE_FILE_BASE64 }} | base64 --decode > app/${{ secrets.KEYSTORE_STORE_FILE }}
          ./gradlew assembleRelease \
            -PMYAPP_UPLOAD_STORE_FILE='${{ secrets.KEYSTORE_STORE_FILE }}' \
            -PMYAPP_UPLOAD_KEY_ALIAS='${{ secrets.KEYSTORE_KEY_ALIAS }}' \
            -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' \
            -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_KEY_PASSWORD }}'
          rm -f app/${{ secrets.KEYSTORE_STORE_FILE }}
          echo "✅ 构建完成！"

      - name: Get package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Create git tag
        uses: pkgdeps/git-tag-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
